version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: scheduler-prometheus
    volumes:
      - ./deploy/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090" # Access Prometheus at localhost:9091

  grafana:
    image: grafana/grafana:latest
    container_name: scheduler-grafana
    ports:
      - "3000:3000" # Access Grafana at localhost:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus