global:
  scrape_interval: 5s 

scrape_configs:
  - job_name: 'job_scheduler'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['scheduler:9090']
      - targets: ['host.docker.internal:9091']